<a href="https://colab.research.google.com/github/Cabreraxx9/CSC221_ncabr005/blob/main/Assignment18.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Assignment 18
## CSC 221
- Nicholas Cabrera

### Instructions:
Fill in each code cell below the question. We are following along in Chapter 2 of Python Distilled.

In [66]:
# 2.1 Literals

# Show how to compute hex 3a27 plus binary 110101111 - 30 decimal using Python literals

# INSERT YOUR CODE HERE
a = 0x3a27
b = 0b110101111
x = a + b - 30
print(x)

15288

In [67]:
# 2.2 Expressions
# I'll make you a small file in the cell below. You can just run this.

In [68]:
%%file small_file.txt
I am the first line of the file.
I am the second line. I contain secrets so please don't print me!
I am the last line.
#test line for the last cell. get this to print

Overwriting small_file.txt

In [69]:
# Now fix the code below code and print all the lines of the file EXCEPT line 2
file1 = open('small_file.txt', 'r')
# FIX THE TWO LINES BELOW
#while line = file1.readline():
#    print(line)

line_no = 1
line = file1.readline()
while line:
    if line_no != 2:
        print(line, end='')
    line = file1.readline()
    line_no += 1
file1.close()

I am the first line of the file.
I am the last line.
#test line for the last cell. get this to print

In [70]:
# 2.3 Standard Operators
# Experiment with pow(x, y, modulo). What does modulo do?
# INSERT YOUR CODE HERE
pow(3, 2, 2) #3rd argument is optional and if provided will perform the modular exponentation
#this will give you 2 to the power of 2 divided by the modulo which gives you the remainder

1

In [71]:
# Experiment with round(x, n). What does n do? What about n=2 vs n=-2?
# INSERT YOUR CODE HERE
round(442.2567, -2) # n rounds the number of decimal places to the right
                    # -n round the number of decimals to the left

400.0

In [72]:
# 2.4 In-Place Assignment
# What should a = [1, 2, 3] followed by a += [7, 6, 5] do? Show me!
# INSERT YOUR CODE HERE
a = [1, 2, 3]
a += [7, 6, 5]
print(a) # its concatanates both lists

[1, 2, 3, 7, 6, 5]

In [73]:
# What should a = [1, 2, 3] followed by a *= 4 do? Show me!
# INSERT YOUR CODE HERE
a = [1, 2, 3]
a *= 4
print(a) #makes 4 lists into one list

[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]

In [74]:
# 2.5 Object Comparison
# Make an exanmple showing the difference between == and is.
# INSERT YOUR CODE HERE
a = [1,2,3]
b = [1,2,3]

a is b

#false because a isnt identical to b. Only use if you expect to have the same identity

False

In [75]:
a = [1,2,3]
b = [1,2,3]

a == b
# == widely used for all comparisons unless you expect objects to be identical

True

In [76]:
# 2.7 Boolean Expressions and Truth
# Why does the code below only output 'Ned'?
def ned():
    print('Ned')
    return False
def lecky():
    print("lecky")
    return False;
if ned() and lecky():
    print('wrote this')

# YOUR EXPLANATION HERE
# The function ned is returning False and prints only ned because the function ned isnt True.
#so therefore the next function isnt evaluated
#if ned() was True it would evaluate and print lecky()

Ned

In [89]:
# 2.8 Conditional Expressions
# Convert the code called out into a one-line conditional expression...
# And what does that format do?
import random
random.seed(42)

def above_or_below():
    x = random.randint(1,100)
    # MAKE THE FOLLOWING 4 LINES INTO ONE CONDITIONAL EXPRESSION
    #if x < 50:
        #y = -1
    #else:
        #y = +1
    #return y
    y = -1 if x < 50 else 1
    return y
for i in range(10):
    # WHAT DOES THIS LINE DO?
    print(format(above_or_below(),"+d")) #does this line call the function and get a random number and check the condition?

+1
-1
-1
+1
-1
-1
-1
-1
+1
-1

In [78]:
# 2.9 Iterables
# Show an example of every iterable in Table 2.5

# INSERT YOUR CODE HERE
name = ["Nick", "John", "Matt", "Andre"]
for x in name:
  print(x)

Nick
John
Matt
Andre

In [79]:
#unpacking
name = ("Nick", "John", "Matt", "Andre")

(Cabrera, Clemons, Hughey, Leon) = name

print(Cabrera)
print(Clemons)
print(Hughey)
print(Leon)

Nick
John
Matt
Andre

In [80]:
#membership
x = [1,2,3,4,5]
if 1 in x:
  print("im 1 and im in the list")

im 1 and im in the list

In [81]:
x = [1,2,3,4,5]
if 6 not in x:
  print("im 6 and im not in the list")

im 6 and im not in the list

In [82]:
#expansion
items = [1,2,3]
x = [9,8,7,*items]
print(x)

[9, 8, 7, 1, 2, 3]

In [83]:
# 2.10 Operations on Sequences
# Show that the example at the end pof section 2.10 are correct
# The code starts with
a = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
print(a[2:5])
#code is correct and uses the slicing operator to get index 2 through 5 but not including 5

[2, 3, 4]

In [84]:
# 2.11 Operations on Mutable Sequences
# Create a list with the first 2 million positive integers in it ([1, 2, 3, ... , 2,000,000])
# Replace the centermost 1,000,000 integers with the string 'MiddleStuff'
# Figure out some way to print this and look at len(this) to demonstrate that it works

# INSERT YOUR CODE HERE

x = []

for i in range(1,2000001):

  x.append(i)
x[999999]= "MiddleStuff"
print(x)

len(x)

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)

2000000

In [85]:
# 2.12 Operations on Sets
# rand1 and rand2 are two independent lists of 1000 numbers between 1 and 1000 inclusive
# What are set1 - set4?
# How many numbers between 1 and 1000 appear in neither list?
import random
random.seed(42)

rand1 = [random.randint(1,1000) for i in range(1000)]
rand2 = [random.randint(1,1000) for i in range(1000)]
set1 = set(rand1) # set1 and set2 are 1000 random numbers in each set
print(set1)

set2 = set(rand2)
print(set2)
set3 = set1 | set2  #This set is the union between set1 and set2
set4 = set1 & set2  #This set is the intersection of set1 and set2
print(len(set1), len(set2), len(set3), len(set4))

{1, 2, 3, 4, 6, 7, 8, 9, 10, 12, 16, 20, 21, 22, 25, 26, 28, 29, 30, 31, 33, 37, 40, 41, 43, 45, 46, 47, 48, 49, 52, 53, 56, 58, 59, 60, 61, 63, 64, 66, 68, 70, 71, 72, 73, 74, 75, 76, 78, 80, 81, 82, 83, 84, 86, 87, 88, 90, 94, 95, 96, 97, 100, 101, 103, 104, 105, 106, 107, 109, 110, 111, 112, 113, 115, 118, 119, 123, 124, 125, 128, 129, 131, 132, 134, 135, 136, 137, 138, 139, 142, 143, 144, 147, 151, 152, 153, 155, 157, 159, 160, 162, 163, 164, 166, 167, 168, 169, 170, 171, 174, 176, 179, 181, 182, 183, 184, 187, 188, 191, 195, 197, 198, 200, 202, 204, 205, 206, 209, 210, 212, 215, 216, 217, 218, 219, 220, 221, 223, 224, 225, 226, 228, 229, 231, 234, 235, 236, 237, 239, 241, 243, 244, 245, 246, 247, 249, 250, 251, 253, 254, 255, 256, 258, 261, 266, 267, 268, 269, 270, 271, 272, 274, 275, 277, 279, 280, 282, 284, 285, 286, 289, 291, 292, 293, 294, 297, 301, 303, 304, 306, 307, 308, 309, 310, 312, 313, 315, 316, 317, 318, 320, 322, 323, 324, 325, 328, 330, 332, 333, 335, 336, 337, 339, 340, 341, 342, 344, 345, 347, 348, 349, 352, 353, 354, 358, 359, 360, 361, 363, 364, 367, 368, 371, 372, 373, 374, 379, 380, 383, 388, 389, 390, 391, 392, 393, 394, 395, 399, 400, 404, 406, 409, 410, 411, 413, 414, 415, 416, 417, 418, 419, 421, 422, 423, 425, 426, 430, 431, 433, 434, 436, 437, 438, 439, 441, 442, 445, 446, 447, 449, 451, 453, 454, 457, 460, 461, 463, 465, 466, 467, 468, 469, 470, 471, 472, 473, 474, 476, 477, 478, 479, 480, 482, 485, 487, 489, 493, 497, 498, 499, 500, 501, 506, 507, 512, 513, 515, 517, 518, 519, 520, 521, 522, 524, 527, 528, 530, 531, 533, 534, 536, 541, 542, 544, 546, 547, 550, 551, 552, 553, 554, 556, 557, 559, 560, 562, 563, 564, 565, 566, 567, 568, 570, 571, 573, 574, 575, 577, 578, 579, 581, 583, 584, 585, 590, 591, 592, 593, 594, 595, 597, 598, 599, 603, 604, 605, 607, 609, 610, 611, 614, 617, 618, 619, 620, 621, 622, 624, 626, 627, 628, 631, 634, 635, 636, 637, 638, 639, 641, 642, 643, 644, 645, 647, 649, 650, 651, 653, 655, 656, 657, 659, 661, 662, 664, 666, 668, 670, 671, 672, 674, 675, 676, 678, 679, 680, 681, 683, 684, 685, 686, 687, 688, 689, 690, 692, 693, 694, 696, 697, 699, 700, 702, 704, 705, 707, 708, 711, 713, 714, 715, 719, 721, 722, 723, 724, 725, 726, 731, 734, 735, 736, 737, 738, 739, 740, 741, 742, 746, 747, 748, 749, 750, 753, 754, 755, 759, 760, 761, 762, 763, 765, 766, 767, 768, 769, 770, 772, 774, 778, 779, 781, 782, 784, 785, 787, 788, 789, 790, 792, 795, 797, 798, 799, 802, 803, 804, 805, 806, 807, 812, 813, 815, 816, 818, 820, 821, 822, 824, 825, 826, 827, 828, 829, 831, 835, 836, 837, 839, 841, 842, 850, 851, 852, 853, 854, 855, 856, 857, 861, 862, 864, 867, 868, 869, 870, 871, 872, 874, 876, 877, 878, 880, 881, 882, 883, 885, 886, 888, 891, 892, 893, 894, 896, 897, 898, 899, 900, 901, 902, 903, 904, 905, 906, 907, 908, 912, 913, 914, 915, 919, 920, 921, 922, 923, 925, 926, 927, 928, 929, 930, 935, 936, 937, 940, 941, 942, 943, 945, 946, 947, 948, 949, 952, 953, 954, 955, 956, 958, 959, 960, 962, 963, 965, 966, 968, 969, 970, 972, 973, 975, 977, 981, 983, 984, 986, 988, 991, 992, 993, 994, 995, 996, 997, 998, 1000}
{2, 3, 9, 10, 11, 13, 15, 16, 18, 20, 21, 22, 23, 26, 27, 30, 32, 34, 35, 37, 38, 39, 41, 42, 43, 45, 47, 48, 51, 52, 53, 54, 55, 56, 58, 62, 63, 65, 67, 71, 72, 73, 74, 76, 77, 78, 81, 83, 84, 88, 89, 91, 93, 94, 96, 100, 101, 102, 103, 105, 106, 108, 109, 110, 111, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 135, 136, 139, 140, 141, 144, 145, 146, 147, 148, 149, 150, 152, 153, 156, 157, 158, 159, 161, 162, 163, 165, 168, 169, 170, 171, 172, 175, 178, 180, 181, 184, 185, 186, 187, 189, 190, 193, 194, 195, 196, 197, 198, 199, 203, 204, 205, 206, 209, 211, 213, 217, 218, 222, 223, 224, 225, 227, 230, 231, 232, 233, 235, 236, 237, 238, 239, 240, 241, 242, 243, 245, 246, 247, 248, 249, 250, 251, 252, 254, 255, 257, 258, 259, 261, 262, 263, 264, 265, 269, 271, 272, 273, 274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285, 286, 287, 290, 292, 294, 295, 296, 299, 300, 301, 302, 303, 304, 305, 306, 307, 309, 310, 312, 313, 314, 315, 317, 319, 320, 323, 324, 325, 326, 329, 330, 331, 332, 333, 335, 336, 337, 338, 339, 340, 341, 342, 345, 346, 347, 349, 350, 353, 354, 356, 357, 359, 361, 364, 368, 370, 371, 372, 374, 375, 377, 378, 380, 381, 384, 385, 387, 389, 390, 391, 392, 393, 394, 396, 398, 405, 406, 407, 408, 411, 413, 414, 415, 417, 418, 419, 420, 421, 422, 424, 425, 426, 427, 430, 431, 432, 435, 436, 439, 440, 442, 443, 444, 445, 446, 447, 449, 450, 451, 452, 453, 454, 455, 456, 458, 459, 462, 465, 466, 467, 468, 471, 473, 474, 476, 477, 480, 481, 482, 483, 484, 485, 488, 490, 491, 494, 495, 496, 497, 500, 501, 502, 503, 504, 505, 506, 507, 508, 509, 510, 511, 513, 514, 515, 519, 520, 521, 522, 527, 530, 531, 532, 535, 536, 538, 539, 544, 546, 547, 549, 550, 551, 552, 553, 554, 555, 556, 557, 558, 560, 563, 564, 565, 566, 567, 568, 569, 570, 571, 572, 575, 577, 578, 579, 580, 583, 584, 586, 588, 589, 590, 591, 593, 594, 596, 598, 599, 600, 601, 602, 603, 604, 605, 607, 609, 610, 611, 612, 613, 614, 615, 619, 621, 622, 624, 625, 631, 633, 634, 635, 636, 637, 638, 639, 641, 642, 643, 644, 645, 646, 647, 649, 651, 652, 654, 655, 658, 661, 662, 664, 665, 666, 667, 668, 671, 674, 675, 676, 677, 678, 679, 680, 683, 685, 686, 687, 689, 691, 692, 693, 694, 695, 698, 699, 700, 701, 703, 704, 706, 707, 708, 709, 710, 711, 714, 715, 716, 717, 718, 719, 720, 721, 723, 724, 725, 726, 727, 729, 733, 734, 736, 738, 739, 740, 742, 744, 745, 749, 750, 752, 753, 757, 758, 761, 763, 764, 765, 766, 767, 768, 769, 771, 773, 774, 775, 777, 778, 779, 780, 781, 782, 783, 784, 786, 792, 793, 794, 795, 797, 800, 801, 802, 806, 807, 808, 809, 810, 811, 812, 816, 817, 819, 822, 824, 825, 826, 828, 831, 833, 834, 839, 841, 842, 843, 844, 845, 846, 847, 849, 850, 851, 852, 853, 854, 855, 857, 858, 859, 860, 862, 866, 867, 869, 870, 871, 872, 873, 874, 875, 876, 877, 879, 880, 881, 882, 883, 885, 886, 887, 890, 891, 892, 894, 896, 898, 901, 902, 903, 906, 907, 909, 911, 913, 921, 923, 924, 925, 926, 930, 931, 932, 933, 935, 936, 938, 939, 942, 944, 947, 950, 952, 956, 957, 958, 962, 963, 964, 965, 966, 967, 968, 969, 970, 971, 972, 973, 974, 975, 978, 981, 982, 984, 985, 986, 987, 988, 989, 990, 991, 992, 993, 994, 995, 997, 998}
637 649 884 402

In [86]:
# 2.14 List, Set, and Dictionary Comprehensions
# Use a dictionary comprehension to create a dictionary that contains the square
# and square root of the factorials from 0 to 100
import math

# Hint: Make a list of the first 100 factorials
def factorial(n):
    fact = 1
    for i in range(1, n+1):
        fact *= i
    return fact
fact_100 = [factorial(x) for x in range(1, 101)]
print(fact_100)

dict1 = {n: (n**2, math.sqrt(math.factorial(n))) for n in range(101)}
print(dict1)

[1, 2, 6, 24, 120, 720, 5040, 40320, 362880, 3628800, 39916800, 479001600, 6227020800, 87178291200, 1307674368000, 20922789888000, 355687428096000, 6402373705728000, 121645100408832000, 2432902008176640000, 51090942171709440000, 1124000727777607680000, 25852016738884976640000, 620448401733239439360000, 15511210043330985984000000, 403291461126605635584000000, 10888869450418352160768000000, 304888344611713860501504000000, 8841761993739701954543616000000, 265252859812191058636308480000000, 8222838654177922817725562880000000, 263130836933693530167218012160000000, 8683317618811886495518194401280000000, 295232799039604140847618609643520000000, 10333147966386144929666651337523200000000, 371993326789901217467999448150835200000000, 13763753091226345046315979581580902400000000, 523022617466601111760007224100074291200000000, 20397882081197443358640281739902897356800000000, 815915283247897734345611269596115894272000000000, 33452526613163807108170062053440751665152000000000, 1405006117752879898543142606244511569936384000000000, 60415263063373835637355132068513997507264512000000000, 2658271574788448768043625811014615890319638528000000000, 119622220865480194561963161495657715064383733760000000000, 5502622159812088949850305428800254892961651752960000000000, 258623241511168180642964355153611979969197632389120000000000, 12413915592536072670862289047373375038521486354677760000000000, 608281864034267560872252163321295376887552831379210240000000000, 30414093201713378043612608166064768844377641568960512000000000000, 1551118753287382280224243016469303211063259720016986112000000000000, 80658175170943878571660636856403766975289505440883277824000000000000, 4274883284060025564298013753389399649690343788366813724672000000000000, 230843697339241380472092742683027581083278564571807941132288000000000000, 12696403353658275925965100847566516959580321051449436762275840000000000000, 710998587804863451854045647463724949736497978881168458687447040000000000000, 40526919504877216755680601905432322134980384796226602145184481280000000000000, 2350561331282878571829474910515074683828862318181142924420699914240000000000000, 138683118545689835737939019720389406345902876772687432540821294940160000000000000, 8320987112741390144276341183223364380754172606361245952449277696409600000000000000, 507580213877224798800856812176625227226004528988036003099405939480985600000000000000, 31469973260387937525653122354950764088012280797258232192163168247821107200000000000000, 1982608315404440064116146708361898137544773690227268628106279599612729753600000000000000, 126886932185884164103433389335161480802865516174545192198801894375214704230400000000000000, 8247650592082470666723170306785496252186258551345437492922123134388955774976000000000000000, 544344939077443064003729240247842752644293064388798874532860126869671081148416000000000000000, 36471110918188685288249859096605464427167635314049524593701628500267962436943872000000000000000, 2480035542436830599600990418569171581047399201355367672371710738018221445712183296000000000000000, 171122452428141311372468338881272839092270544893520369393648040923257279754140647424000000000000000, 11978571669969891796072783721689098736458938142546425857555362864628009582789845319680000000000000000, 850478588567862317521167644239926010288584608120796235886430763388588680378079017697280000000000000000, 61234458376886086861524070385274672740778091784697328983823014963978384987221689274204160000000000000000, 4470115461512684340891257138125051110076800700282905015819080092370422104067183317016903680000000000000000, 330788544151938641225953028221253782145683251820934971170611926835411235700971565459250872320000000000000000, 24809140811395398091946477116594033660926243886570122837795894512655842677572867409443815424000000000000000000, 1885494701666050254987932260861146558230394535379329335672487982961844043495537923117729972224000000000000000000, 145183092028285869634070784086308284983740379224208358846781574688061991349156420080065207861248000000000000000000, 11324281178206297831457521158732046228731749579488251990048962825668835325234200766245086213177344000000000000000000, 894618213078297528685144171539831652069808216779571907213868063227837990693501860533361810841010176000000000000000000, 71569457046263802294811533723186532165584657342365752577109445058227039255480148842668944867280814080000000000000000000, 5797126020747367985879734231578109105412357244731625958745865049716390179693892056256184534249745940480000000000000000000, 475364333701284174842138206989404946643813294067993328617160934076743994734899148613007131808479167119360000000000000000000, 39455239697206586511897471180120610571436503407643446275224357528369751562996629334879591940103770870906880000000000000000000, 3314240134565353266999387579130131288000666286242049487118846032383059131291716864129885722968716753156177920000000000000000000, 281710411438055027694947944226061159480056634330574206405101912752560026159795933451040286452340924018275123200000000000000000000, 24227095383672732381765523203441259715284870552429381750838764496720162249742450276789464634901319465571660595200000000000000000000, 2107757298379527717213600518699389595229783738061356212322972511214654115727593174080683423236414793504734471782400000000000000000000, 185482642257398439114796845645546284380220968949399346684421580986889562184028199319100141244804501828416633516851200000000000000000000, 16507955160908461081216919262453619309839666236496541854913520707833171034378509739399912570787600662729080382999756800000000000000000000, 1485715964481761497309522733620825737885569961284688766942216863704985393094065876545992131370884059645617234469978112000000000000000000000, 135200152767840296255166568759495142147586866476906677791741734597153670771559994765685283954750449427751168336768008192000000000000000000000, 12438414054641307255475324325873553077577991715875414356840239582938137710983519518443046123837041347353107486982656753664000000000000000000000, 1156772507081641574759205162306240436214753229576413535186142281213246807121467315215203289516844845303838996289387078090752000000000000000000000, 108736615665674308027365285256786601004186803580182872307497374434045199869417927630229109214583415458560865651202385340530688000000000000000000000, 10329978488239059262599702099394727095397746340117372869212250571234293987594703124871765375385424468563282236864226607350415360000000000000000000000, 991677934870949689209571401541893801158183648651267795444376054838492222809091499987689476037000748982075094738965754305639874560000000000000000000000, 96192759682482119853328425949563698712343813919172976158104477319333745612481875498805879175589072651261284189679678167647067832320000000000000000000000, 9426890448883247745626185743057242473809693764078951663494238777294707070023223798882976159207729119823605850588608460429412647567360000000000000000000000, 933262154439441526816992388562667004907159682643816214685929638952175999932299156089414639761565182862536979208272237582511852109168640000000000000000000000, 93326215443944152681699238856266700490715968264381621468592963895217599993229915608941463976156518286253697920827223758251185210916864000000000000000000000000]
{0: (0, 1.0), 1: (1, 1.0), 2: (4, 1.4142135623730951), 3: (9, 2.449489742783178), 4: (16, 4.898979485566356), 5: (25, 10.954451150103322), 6: (36, 26.832815729997478), 7: (49, 70.9929573971954), 8: (64, 200.79840636817812), 9: (81, 602.3952191045344), 10: (100, 1904.9409439665053), 11: (121, 6317.974358922328), 12: (144, 21886.105181141756), 13: (169, 78911.47445080469), 14: (196, 295259.70128007646), 15: (225, 1143535.905863913), 16: (256, 4574143.623455652), 17: (289, 18859677.306253146), 18: (324, 80014834.28544985), 19: (361, 348776576.6344294), 20: (400, 1559776268.6284978), 21: (441, 7147792818.185865), 22: (484, 33526120082.37171), 23: (529, 160785623545.40588), 24: (576, 787685471322.9382), 25: (625, 3938427356614.6914), 26: (676, 20082117944245.96), 27: (729, 104349745809073.98), 28: (784, 552166953567228.5), 29: (841, 2973510046012910.5), 30: (900, 1.6286585271694956e+16), 31: (961, 9.067986906793549e+16), 32: (1024, 5.1296280268036346e+17), 33: (1089, 2.9467469553410734e+18), 34: (1156, 1.7182339742875652e+19), 35: (1225, 1.016520927791757e+20), 36: (1296, 6.099125566750543e+20), 37: (1369, 3.7099532465014094e+21), 38: (1444, 2.28696877430935e+22), 39: (1521, 1.428211541796153e+23), 40: (1600, 9.032802905233224e+23), 41: (1681, 5.783815921445271e+24), 42: (1764, 3.7483411234209725e+25), 43: (1849, 2.4579516484946126e+26), 44: (1936, 1.6304206741784308e+27), 45: (2025, 1.0937194378152021e+28), 46: (2116, 7.417966136220958e+28), 47: (2209, 5.085501366740237e+29), 48: (2304, 3.523338699662023e+30), 49: (2401, 2.4663370897634156e+31), 50: (2500, 1.743963680863606e+32), 51: (2601, 1.2454391808865587e+33), 52: (2704, 8.980989654316716e+33), 53: (2809, 6.538259159791715e+34), 54: (2916, 4.804619624270389e+35), 55: (3025, 3.5632012788584193e+36), 56: (3136, 2.666455677120592e+37), 57: (3249, 2.013129889124823e+38), 58: (3364, 1.5331540468207618e+39), 59: (3481, 1.1776379687564844e+40), 60: (3600, 9.121944481710788e+40), 61: (3721, 7.124466393192017e+41), 62: (3844, 5.609810447812648e+42), 63: (3969, 4.452649004137245e+43), 64: (4096, 3.562119203309796e+44), 65: (4225, 2.8718723147247465e+45), 66: (4356, 2.3331200978034607e+46), 67: (4489, 1.909741105966688e+47), 68: (4624, 1.574812859496909e+48), 69: (4761, 1.3081378078327272e+49), 70: (4900, 1.094466613011557e+50), 71: (5041, 9.222139602976429e+50), 72: (5184, 7.825244940376377e+51), 73: (5329, 6.685892207860283e+52), 74: (5476, 5.751421947239992e+53), 75: (5625, 4.9808775141931966e+54), 76: (5776, 4.3422283469044446e+55), 77: (5929, 3.8102899106011066e+56), 78: (6084, 3.365156932181068e+57), 79: (6241, 2.991016905800262e+58), 80: (6400, 2.675246849288189e+59), 81: (6561, 2.4077221643593697e+60), 82: (6724, 2.1802851503903892e+61), 83: (6889, 1.986334304622628e+62), 84: (7056, 1.8205054612841327e+63), 85: (7225, 1.6784231035053556e+64), 86: (7396, 1.5565055535934568e+65), 87: (7569, 1.4518117296604018e+66), 88: (7744, 1.361920123419132e+67), 89: (7921, 1.2848328747704294e+68), 90: (8100, 1.2188994890809338e+69), 91: (8281, 1.1627560052213891e+70), 92: (8464, 1.1152763807523813e+71), 93: (8649, 1.0755335917960172e+72), 94: (8836, 1.0427685057848377e+73), 95: (9025, 1.016365017512855e+74), 96: (9216, 9.958302741285533e+74), 97: (9409, 9.807790764615756e+75), 98: (9604, 9.709217501366034e+76), 99: (9801, 9.660549437994929e+77), 100: (10000, 9.66054943799493e+78)}

In [87]:
# 2.15 Generator Expression
# Show that the code that begins with
# Read a file
f = open("small_file.txt")
# in Section 2.15 actually print all the lines in a file that begin with a '#'
# INSERT YOUR CODE HERE

lines = (t.strip() for t in f)

comments = (t for t in lines if t[0] == "#")
for x in comments:
  print(x)

#test line for the last cell. get this to print